### PR TITLE
First stab at docs

### PR DESCRIPTION
**Pull request by paf31**
@garyb @joneshf Could you please review?

I didn't document `Clown` and `Joker` because I don't fully understand how they are used in isolation without the type class machinery of the clown/joker paper.

### CODE REVIEW

**Comment by paf31** [comment]
@garyb Ping. This look ok?

**Comment by garyb** [comment]
Yep, all looks good to me :+1:

**Comment by garyb** [comment]
I read this earlier but forgot to comment.

**Comment by paf31** [comment]
Cool, thanks. I'm still a bit uncertain about the clown/joker stuff, maybe we can fill those in later?

**Comment by garyb** [comment]
Yeah, I'm not that familiar with them either, it was @DylanLukes who added those. I just did the Bifunctor/Biapplicative/Bifoldable/Bitraversable stuff.

**Comment by DylanLukes** [comment]
It's based on the presentation of bifunctors given here:

http://strictlypositive.org/CJ.pdf

**Comment by paf31** [comment]
@DylanLukes Thanks, I was reading that to try to document them, but I couldn't figure out how to give any useful example without the type class machinery given in the paper.

**Comment by DylanLukes** [comment]
Edward's Haskell package is what I worked off of, so it should be pretty helpful :).

**Comment by paf31** [comment]
:smile:

**Comment by DylanLukes** [comment]
:beers:

**Pull request merged**
